// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtG4By1UnJuI8ANXFvlhD3clm6NJzXuQQ',
    appId: '1:652907939226:web:7dd11b4d7d830e2778e623',
    messagingSenderId: '652907939226',
    projectId: 'fireexp474',
    authDomain: 'fireexp474.firebaseapp.com',
    storageBucket: 'fireexp474.firebasestorage.app',
    measurementId: 'G-PLSMNDSXPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLmwFigpDTqUHKULFwz9BVpAjTWpGa1ck',
    appId: '1:652907939226:android:2c8a6d43c2b6681578e623',
    messagingSenderId: '652907939226',
    projectId: 'fireexp474',
    storageBucket: 'fireexp474.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr-2QkvvQ3fV54dgHPLwEZjCJVFgrlO9c',
    appId: '1:652907939226:ios:fec04284c40cd10278e623',
    messagingSenderId: '652907939226',
    projectId: 'fireexp474',
    storageBucket: 'fireexp474.firebasestorage.app',
    iosBundleId: 'com.example.fireExp474',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr-2QkvvQ3fV54dgHPLwEZjCJVFgrlO9c',
    appId: '1:652907939226:ios:fec04284c40cd10278e623',
    messagingSenderId: '652907939226',
    projectId: 'fireexp474',
    storageBucket: 'fireexp474.firebasestorage.app',
    iosBundleId: 'com.example.fireExp474',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtG4By1UnJuI8ANXFvlhD3clm6NJzXuQQ',
    appId: '1:652907939226:web:940522cd2ae70cf578e623',
    messagingSenderId: '652907939226',
    projectId: 'fireexp474',
    authDomain: 'fireexp474.firebaseapp.com',
    storageBucket: 'fireexp474.firebasestorage.app',
    measurementId: 'G-2HBNPSP98F',
  );
}
